name: prodiution-build
on:
  push:
    branches: [source]
  pull_request:
    branches: [source]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create CNAME
        run: echo "iamdavidabayomi.me" >> ./public/CNAME

      - name: Deploy
        run: |
          git config --global user.name iamdavidabayomi
          git config --global user.email iamdavidabayomi@gmail.com
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          github_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
